### ISSUE TITLE
Remove Node modules folder from GIT

### ISSUE THREAD

**Issue by aniketnale41** [ananthakrishnantm/Food-Blog#2]
node_modules are not the usual folder to be uploaded on git.

Running `npm install` in the project folder will install all the required npm modules and create node_modules folder according to the modules mentioned in the package.json file.

refer this : - https://dev.to/grawl/why-you-dont-have-to-commit-nodemodules-folder-33nm

**Comment by aniketnale41** [comment]
https://github.com/aniketnale41/Food-Blog
Updated commit here with the fix, if you want to take/create pull request here to merge it directly : 
https://github.com/ananthakrishnantm/Food-Blog/compare/main...aniketnale41:Food-Blog:main

**Comment by ananthakrishnantm** [comment]
i solved it i already had two commits in my branch so removed it along with that :D. Thanks for notifying it
